<template>
  <div class="box">
    <div class="tab" v-for="(tab, index) of tabs" :class="{ 'flipped': tab.isFlipped, 'possible': tab.isPossible }" @click="tabs[index].isFlipped = true" :key="index">
      <span v-if="tab.isFlipped">☺</span>
      <span v-else>{{index + 1}}</span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Box',
  props: [ 'tabs' ]
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.box {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  border: 2px solid #A8C686;
  font-family: monospace;
  margin-top: 4rem;
}

.box > * {
  color: #9D9C62;
  font-size: 24px;
  font-weight: bold;
  padding: 1rem;
  flex-grow: 1;
  flex-shrink: 1;
  flex-basis: 50px;
  transition: transform 1s ease;
  border: 1px solid #A8C686;
}

.flipped {
  background: #dad9a6;
	-webkit-animation: swing-top-fwd 0.15s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: swing-top-fwd 0.15s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

.possible {
  background: lightgreen;
}

@media screen and (max-width: 765px) {
  .box {
    flex-direction: column;
  }

  .box > * {
    flex-basis: 25px;
    padding: 0.5rem;
    border: 1px solid #A8C686;
  }

  .flipped {
	-webkit-animation: flip-vertical-right 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
	        animation: flip-vertical-right 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-7-7 16:37:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-top-fwd
 * ----------------------------------------
 */
@-webkit-keyframes swing-top-fwd {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
    -webkit-transform-origin: top;
            transform-origin: top;
  }
  100% {
    -webkit-transform: rotateX(180deg);
            transform: rotateX(180deg);
    -webkit-transform-origin: top;
            transform-origin: top;
  }
}
@keyframes swing-top-fwd {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
    -webkit-transform-origin: top;
            transform-origin: top;
  }
  100% {
    -webkit-transform: rotateX(180deg);
            transform: rotateX(180deg);
    -webkit-transform-origin: top;
            transform-origin: top;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-7-7 17:56:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-vertical-right
 * ----------------------------------------
 */
@-webkit-keyframes flip-vertical-right {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(180deg);
            transform: rotateY(180deg);
  }
}
@keyframes flip-vertical-right {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(180deg);
            transform: rotateY(180deg);
  }
}

</style>
